### ISSUE TITLE
Infomap for marine data

### ISSUE THREAD

**Issue by PatrickPata** [mapequation/bioregions#35]
Hi,

Is there a way for me to use the Infomap Bioregions webapp to do clustering with marine species data? I'm very interested in exploring this method but when I loaded my marine species distribution list, the clusters were set to the nearest land polygons.

**Comment by danieledler** [comment]
Hi. Sorry I have missed this for some reason. By default we have a "Clip to land" switch toggled on. You can toggle that off to show data outside land. It only changes the _visual_ output, so if you export the results you can clip it in QGIS or similar software.
