### ISSUE TITLE
Can't upload my species distribution .csv file

### ISSUE THREAD

**Issue by TiagoVieiraBotany** [mapequation/bioregions#36]
Hello,
I have not been successful in uploading species distribution .csv files in the last few days. The same file which I was successful before. Is there a bug going on? I am using chrome. Anyone else went through this?

**Comment by danieledler** [comment]
Hi, I'm able to load the files I tested, can you describe what happens?

**Comment by TiagoVieiraBotany** [comment]
It keeps loading and never ends... I am attaching the .csv file.
[geodata_infomaps.txt](https://github.com/mapequation/bioregions/files/4397353/geodata_infomaps.txt)

**Comment by danieledler** [comment]
Strange, I'm able to load that file. How far did it come, where you able to select species and coordinates columns?

**Comment by TiagoVieiraBotany** [comment]
Yeah, weird. No, the box menu to select species/coordinates just does not appear...
I reinstalled Java, but the issue still. Thanks a lot for the quick answers anyway.

**Comment by danieledler** [comment]
Which browser and version are you using? Can you try another browser and see if you get the same problem? It only requires JavaScript enabled, so no Java required, they are easily mixed by name :)

**Comment by TiagoVieiraBotany** [comment]
Google Chrome version 80.0.3987.149 (64 bits). I tried microsoft edge and mozilla firefox, both not successful. Also, I just noticed that the example files can't get loaded as well (Global mammals and neotropical mammals). It keeps with the not ending "loading files" screen.

**Comment by danieledler** [comment]
Oh, I found the issue! I loaded it from the old address bioregions.mapequation.org (where it still works) but the new address mapequation.org/bioregions, which we link to from mapequation.org, have got the loading error now for some reason. I will check a bit later today, thanks for reporting the issue!

**Comment by TiagoVieiraBotany** [comment]
Oh, great! Yeah, now it works fine. Thanks a lot!

**Comment by angelacano** [comment]
Hi Daniel! I can't upload my csv file. Actually when I click on Load species distribution data... nothing happens. I'm using Chrome, but I also tried explorer. I tried bioregions.mapequation.org. Thank you for any help :)

**Comment by danieledler** [comment]
Hi @angelacano, thanks, now it should be fixed! Please try again.

**Comment by angelacano** [comment]
Hi @danieledler! I just tried, but nothing happens when I click on Load species distribution data... :(

**Comment by danieledler** [comment]
@angelacano, maybe it is a cache thing, can you try holding down shift and reload the page and see if it works then?

**Comment by angelacano** [comment]
That worked @danieledler! thank you very much!
