### ISSUE TITLE
Error: dn.format is not a function

### ISSUE THREAD

**Issue by jmandarwin** [mapequation/bioregions#56]
I can't export tables or shp files, I get this error. Analysis is done ok, however. Any help would be appreciated.

**Comment by danieledler** [comment]
Hi. Sorry there was a bug introduced last week that I missed to test, but now fixed in 828d214. Just reload and make sure you get version 1.3.1 (visible above the red load data button), and it should work again!

**Comment by jmandarwin** [comment]
Thank you!!!
